name = "Train World"
author = "darkk1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "774756e59b5bee5ac229adbc7327555a06149bb68688dc2579aacc753af111ba"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
